### PR TITLE
Lesson 1 3

### PR DESCRIPTION
**Pull request by romymedan**

### CODE REVIEW

**Review by MalinSP — CHANGES_REQUESTED** [review]
Screenshot 2023-10-17 at 9 44 21 AM
React requires that the first letter of components be capitalized

**Comment by romymedan** [comment]
> Screenshot 2023-10-17 at 9 44 21 AM React requires that the first letter of components be capitalized

Hi @MalinSP ,
I ran multiple times and couldn't see the error you are seeing  :(
Am I missing something? Please help me to understand.
Thanks!
Screenshot 2023-10-17 at 8 19 52 PM

**Comment by romymedan** [comment]
> > Screenshot 2023-10-17 at 9 44 21 AM React requires that the first letter of components be capitalized
> 
> Hi @MalinSP , I ran multiple times and couldn't see the error you are seeing :( Am I missing something? Please help me to understand. Thanks! Screenshot 2023-10-17 at 8 19 52 PM

okay, I think I got it now :)
I renamed this file in this branch, somehow it renames lowercase. I deleted the old file, hope it helped.

**Review by MalinSP — APPROVED** [review]
Now everything works as expected. Good job!

**Pull request merged**
